### ISSUE TITLE
Maven, multi-module & standard directories

### ISSUE THREAD

**Issue by levonk** [int08h/nearenough#1]
Hi It would be it be great if this was a maven multi-module project:

pom.xml
|-protocol
   |- src
      |- main
         |- java
      |- test
|-server
|-client

**Comment by int08h** [comment]
Agreed! In fact there's an item in the [ROADMAP](https://github.com/int08h/nearenough/blob/master/ROADMAP.md) to add proper Maven support.

My Maven skills are non-existent. Contributions welcome!

Related #2

**Comment by int08h** [comment]
Making note for future potential contributors: 

The Netty, JUnit, and Hamcrest dependencies are straight-forward. The wrinkle is with [EdDSA-Java](https://github.com/str4d/ed25519-java) as the current [Maven artifact](https://mvnrepository.com/artifact/net.i2p.crypto/eddsa/0.1.0) for it is out of date.

The EdDSA-Java `jar` bundled with Nearenough was created from `master` specifically https://github.com/str4d/ed25519-java/commit/dc9f58f2c874463c15465326efc040d17a627b3a. A potential Maven pom would need to account for this.

**Comment by int08h** [comment]
Nearenough is now built via Gradle, using standard build conventions. 

Closing
